# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp

    # This version must be equal to everything after the '+' in the purchases-kmp version.
    pod 'PurchasesHybridCommon', '13.3.0'

end
